# Generated by Django 4.2.30 on 2026-06-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_remove_movie_recommendation_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
