# Generated by Django 4.2.30 on 2026-07-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_movie_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="poster_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
